### ISSUE TITLE
Magemonkey cause error after install data-migration-tool via composer 

### ISSUE THREAD

**Issue by AlexNevskyV** [ebizmarts/magento2-magemonkey#35]
Magemonkey 3.0.7
Magento 2.1.1
After installed data-migration-tool via composer i get error

```
[UnexpectedValueException]                                                                                              
Package ebizmarts/magento2-magemonkey's source key should be specified as {"type": ..., "url": ..., "reference": ...},  
{"type":"git","url":"https:\/\/github.com\/ebizmarts\/magento2-magemonkey.git","reference":null} given.
```

Report magento file:

```
a:4:{i:0;s:222:"Package ebizmarts/magento2-magemonkey's source key should be specified as {"type": ..., "url": ..., "reference": ...},
{"type":"git","url":"https:\/\/github.com\/ebizmarts\/magento2-magemonkey.git","reference":null} given.";i:1;s:7721:"#0 /public_html/vendor/composer/composer/src/Composer/Repository/FilesystemRepository.php(63): Composer\Package\Loader\ArrayLoader->load(Array)
#1 /public_html/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php(179): Composer\Repository\FilesystemRepository->initialize()
#2 /public_html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(235): Composer\Repository\ArrayRepository->getPackages()
#3 /public_html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#4 /public_html/vendor/composer/composer/src/Composer/Factory.php(354): Composer\Plugin\PluginManager->loadInstalledPlugins()
#5 /public_html/vendor/composer/composer/src/Composer/Factory.php(532): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), Array, false)
#6 /public_html/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/...')
#7 /public_html/vendor/magento/framework/Composer/ComposerInformation.php(362): Magento\Framework\Composer\ComposerFactory->create()
#8 /public_html/vendor/magento/framework/Composer/ComposerInformation.php(375): Magento\Framework\Composer\ComposerInformation->getComposer()
#9 /public_html/vendor/magento/framework/Composer/ComposerInformation.php(242): Magento\Framework\Composer\ComposerInformation->getLocker()
#10 /public_html/vendor/magento/framework/App/ProductMetadata.php(104): Magento\Framework\Composer\ComposerInformation->getSystemPackages()
#11 /public_html/vendor/magento/framework/App/ProductMetadata.php(65): Magento\Framework\App\ProductMetadata->getSystemPackageVersion()
#12 /public_html/vendor/magento/module-admin-notification/Model/Feed.php(208): Magento\Framework\App\ProductMetadata->getVersion()
#13 /public_html/vendor/magento/module-admin-notification/Model/Feed.php(138): Magento\AdminNotification\Model\Feed->getFeedData()
#14 /public_html/vendor/magento/module-admin-notification/Observer/PredispatchAdminActionControllerObserver.php(51): Magento\AdminNotification\Model\Feed->checkUpdate()
#15 /public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\AdminNotification\Observer\PredispatchAdminActionControllerObserver->execute(Object(Magento\Framework\Event\Observer))
#16 /public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\AdminNotification\Observer\PredispatchAdminActionControllerObserver), Object(Magento\Framework\Event\Observer))
#17 /public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#18 /public_html/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#19 /public_html/vendor/magento/framework/App/Action/Action.php(91): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#20 /public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#23 /public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#24 /public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#27 /public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /public_html/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#33 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#34 /public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#39 /public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#40 {main}";s:3:"url";s:94:"/admin/admin/index/index/key/6de821db5278e72d874d95ad93d9a578b4c309b2e1e1fb6a23af4d1d35b9f573/";s:11:"script_name";s:10:"/index.php";}
```

**Comment by Santiagoebizmarts** [comment]
Hello @AlexNevskyV 
Can you elaborate more on when do you get this error message?
Are you trying to update MageMonkey?

Please read our [guidelines](https://github.com/ebizmarts/magento2-magemonkey/wiki/Issue-reporting-guidelines) to see what should be added for a full report on the issue.

Regards.
