### ISSUE TITLE
500 Server after installing via composer

### ISSUE THREAD

**Issue by kevando** [ebizmarts/magento2-magemonkey#8]
Is it possible to put the installation instructions here on github? 

I ran the install from the pdf and now I get a 500 server error and this is the first extension I installed so now I'm sorta clueless how to troubleshoot.

**Comment by kevando** [comment]
`[Wed Feb 24 14:37:09.191298 2016] [:error] [pid 30593] [client 127.0.0.1:52442] PHP Fatal error:  Uncaught exception 'Magento\\Framework\\Exception\\LocalizedException' with message 'Can't create directory /Users/k/Work/www/frameri/magento2/var/generation/Magento/Framework/App/ResourceConnection/.' in /Users/k/Work/www/frameri/magento2/lib/internal/Magento/Framework/Code/Generator.php:103\nStack trace:\n#0 /Users/k/Work/www/frameri/magento2/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\\Framework\\Code\\Generator->generateClass('Magento\\\\Framewo...')\n#1 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('Magento\\\\Framewo...')\n#2 [internal function]: spl_autoload_call('Magento\\\\Framewo...')\n#3 /Users/k/Work/www/frameri/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\\\Framewo...')\n#4 /Users/k/Work/www/frameri/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor('Magento\\\\Framewo...')\n#5 /Users/k/Work/www/frameri/magento2 in /Users/k/Work/www/frameri/magento2/lib/internal/Magento/Framework/Code/Generator.php on line 103`

This is the error message in the apache2 logs FYI, I am still not sure what this means

**Comment by kevando** [comment]
It appears after the installation I needed to update the permissions on var. The following command did it for me

`chmod -R 777`
